# Generated by Django 2.0.5 on 2018-12-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_empleado', models.CharField(max_length=50)),
                ('puntuacion', models.FloatField(default=0.0)),
            ],
        ),
    ]
