# Generated by Django 2.0 on 2018-12-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField()),
                ('descripcion_empleador', models.CharField(max_length=200)),
                ('acuerdos', models.CharField(max_length=150)),
                ('restricciones', models.CharField(max_length=150)),
                ('sueldo_nominal', models.FloatField()),
                ('temporada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellidos_empleado', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_empleado', models.CharField(max_length=50)),
                ('puntuacion', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=25, null=True)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('foto', models.ImageField(upload_to='photos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Categoria')),
                ('usuario_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('codigo_empleador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('tipo_empleador', models.CharField(max_length=25)),
                ('puntuacion', models.FloatField(default=0.0)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=50)),
                ('usuario_empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('ubicacion_empresa', models.CharField(max_length=100)),
                ('puesto_ejercido', models.CharField(max_length=50)),
                ('tareas_realizadas', models.CharField(max_length=150)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('razon_salida', models.CharField(max_length=150)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50)),
                ('grado_desarrollo', models.FloatField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilBuscado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(max_length=150)),
                ('respuesta_correcta', models.CharField(max_length=100)),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PreparacionAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=50)),
                ('grado_academico', models.CharField(max_length=50)),
                ('especializacion', models.CharField(max_length=50)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('fecha_programada', models.DateField()),
                ('hora_programada', models.CharField(max_length=10)),
                ('temas_evaluar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_publicacion', models.CharField(max_length=100)),
                ('requerimientos', models.CharField(max_length=350)),
                ('horarios_empleo', models.CharField(max_length=150)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Categoria')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Empleador')),
                ('perfil_buscado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.PerfilBuscado')),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_empleado', models.FloatField()),
                ('referencia_empleado', models.CharField(max_length=200, null=True)),
                ('puntuacion_empleador', models.FloatField()),
                ('referencia_empleador', models.CharField(max_length=200, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_seleccionada', models.CharField(max_length=150)),
                ('porcentaje_obtenido', models.FloatField()),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Interesado')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='prueba',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Publicacion'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Prueba'),
        ),
        migrations.AddField(
            model_name='interesado',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Publicacion'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Empleado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Empleado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.Empleador'),
        ),
    ]
