# Generated by Django 2.0.5 on 2018-12-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleador',
            options={'ordering': ['nombre_comercial']},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleos.Categoria'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
