# Generated by Django 2.0.5 on 2018-12-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_empleado_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria']},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='categoria',
        ),
    ]
