# Generated by Django 2.0.5 on 2018-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_auto_20181209_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
