# Generated by Django 2.0.5 on 2018-12-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_auto_20181209_1815'),
        ('empleos', '0002_auto_20181209_1810'),
    ]

    operations = [
    ]
