# Generated by Django 2.0.5 on 2018-12-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_merge_20181209_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleos.Categoria'),
            preserve_default=False,
        ),
    ]
