# Generated by Django 2.0.5 on 2018-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_empleado_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default=2, upload_to='photos'),
            preserve_default=False,
        ),
    ]
